import Head from 'next/head'
import Image from 'next/image'
import { useSelector } from 'react-redux'
import NavBar from '../components/NavBar'
import NotificationAlert from '../components/ui-components/NotificationAlert'
import styles from '../styles/Home.module.css'
import Patient from './patient'

export default function Home() {
  const _notificationState = useSelector((state) => state.notificationState.value)
  return (
    <>
    <Patient/>
    </>
  )
{/*       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
}
